spring:
  data:
    jpa:
      repositories:
        enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/worcflo_local?serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver   
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    platform: mysql
#zoom app testing credentials
app:
  zoom:
    clientId : 9b1KizQAQ22NFEpc0ogMfw
    clientSecret : IXD2U9Opp5oq1Qx68KynbEr9w8i71zb9
    redirectUrl : https://oauth.pstmn.io/v1/callback
